application: nonjslocalsearch
version: 9
runtime: python
api_version: 1

handlers:
- url: /(.*\.(gif|png|jpg))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg))
- url: /.*
  script: localSearch.py