application: ajax-apis
version: 2
runtime: python
api_version: 1

handlers:
- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /html
  static_dir: html

- url: /css
  static_dir: css

- url: /
  static_files: html/hello.html
  upload: html/hello.html

- url: /cse-style
  static_files: html/cselement.html
  upload: html/cselement.html

- url: /cse-less-style
  static_files: html/cselement_less_style.html
  upload: html/cselement_less_style.html

- url: /gcfcheck-demo
  static_files: html/google_chrome_frame_detect.html
  upload: html/google_chrome_frame_detect.html

- url: /two-page-search
  static_files: html/two_page_search.html
  upload: html/two_page_search.html

- url: /two-page-search-alt
  static_files: html/two_page_search_hidden_query.html
  upload: html/two_page_search_hidden_query.html

- url: /iframes.*
  script: iframes/main.py
