application: interactivesampler
version: 1
runtime: python
api_version: 1

default_expiration: "4d 5h"

handlers:
- url: /js
  static_dir: js
- url: /popout.html
  static_files: popout.html
  upload: popout.html
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /images
  static_dir: images
- url: /css
  static_dir: css
- url: /codemirror
  static_dir: codemirror
- url: /(.*\.(gif|png|jpg))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg))
- url: /samples/boilerplateHTML/(.*\.html)
  script: boilerplateProxy.py
- url: /index.html
  script: main.py
- url: /samples/js
  static_dir: samples/js
- url: .*
  script: main.py