application: interactivesampler
version: 1
runtime: python
api_version: 1

default_expiration: "4d 5h"

handlers:
- url: /js
  static_dir: js
- url: /popout.html
  static_files: popout.html
  upload: popout.html
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /images
  static_dir: images
- url: /css
  static_dir: css
- url: /codemirror
  static_dir: codemirror
- url: /samples/boilerplateHTML/(.*\.html)
  script: boilerplateProxy.py
- url: /index.html
  script: main.py
- url: /samples/js
  static_dir: samples/js
- url: /save
  script: main.py
- url: /delete
  script: main.py
- url: /get
  script: main.py
- url: /
  script: main.py
- url: /apis/ajax/playground/js
  static_dir: js
- url: /apis/ajax/playground/popout.html
  static_files: popout.html
  upload: popout.html
- url: /apis/ajax/playground/favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /apis/ajax/playground/images
  static_dir: images
- url: /apis/ajax/playground/css
  static_dir: css
- url: /apis/ajax/playground/codemirror
  static_dir: codemirror
- url: /apis/ajax/playground/samples/boilerplateHTML/(.*\.html)
  script: boilerplateProxy.py
- url: /apis/ajax/playground/index.html
  script: main.py
- url: /apis/ajax/playground/samples/js
  static_dir: samples/js
- url: /apis/ajax/playground/save
  script: main.py
- url: /apis/ajax/playground/delete
  script: main.py
- url: /apis/ajax/playground/get
  script: main.py
- url: /apis/ajax/playground/
  script: main.py
- url: /apis/ajax/playground
  script: main.py