application: addressbook
version: 1
runtime: python
api_version: 1

handlers:
- url: /scripts
  static_dir: scripts
- url: /images
  static_dir: images
- url: /styles
  static_dir: styles
  mime_type: text/css
- url: .*
  script: main.py

# - url: (.*)\.css
#   static_files: \1.css
#   upload: (.*\.css)
# - url: /favicon.ico 
#   static_files: img/favicon.ico 
#   upload: img/favicon.ico 
#   mime_type: image/x-icon
